const wallQuestions = { 
        lion: [
            {id:0 , group: 1, title:"Stills"},
            {id:1 , group: 1, title:"King"},
            {id:2 , group: 1, title:"Fry"},
            {id:3 , group: 1, title:"Curry"},
            {id:4 , group: 2, title:"Talk"},
            {id:5 , group: 2, title:"Potatoes"},
            {id:6 , group: 2, title:"Pox"},
            {id:7 , group: 2, title:"Scale"},
            {id:8 , group: 3, title:"Roast"},
            {id:9 , group: 3, title:"Grill"},
            {id:10 , group: 3, title:"Bake"},
            {id:11 , group: 3, title:"Boil"},
            {id:12 , group: 4, title:"Steam"},
            {id:13 , group: 4, title:"Life"},
            {id:14 , group: 4, title:"Banana"},
            {id:15 , group: 4, title:"Motor"},
        ],
        water: [
            {id:0 , group: 1, title:"Killer"},
            {id:1 , group: 1, title:"Spelling"},
            {id:2 , group: 1, title:"Queen"},
            {id:3 , group: 1, title:"Busy"},
            {id:4 , group: 2, title:"Nick"},
            {id:5 , group: 2, title:"Lift"},
            {id:6 , group: 2, title:"Jack"},
            {id:7 , group: 2, title:"Pinch"},
            {id:8 , group: 3, title:"Net"},
            {id:9 , group: 3, title:"King"},
            {id:10 , group: 3, title:"Hornet"},
            {id:11 , group: 3, title:"Bull"},
            {id:12 , group: 4, title:"Ace"},
            {id:13 , group: 4, title:"Break"},
            {id:14 , group: 4, title:"Deuce"},
            {id:15 , group: 4, title:"Love"},
        ],
        twoReeds: [
    {id:0 , group: 1, title:"John"},
    {id:1 , group: 1, title:"Throne"},
    {id:2 , group: 1, title:"Pot"},
    {id:3 , group: 1, title:"Can"},
    {id:4 , group: 2, title:"Pixie"},
    {id:5 , group: 2, title:"Bowl"},
    {id:6 , group: 2, title:"Caesar"},
    {id:7 , group: 2, title:"Crew"},
    {id:8 , group: 3, title:"Hillary"},
    {id:9 , group: 3, title:"Condoleeza"},
    {id:10 , group: 3, title:"Colin"},
    {id:11 , group: 3, title:"Rex"},
    {id:12 , group: 4, title:"Woody"},
    {id:13 , group: 4, title:"Sarge"},
    {id:14 , group: 4, title:"Jessie"},
    {id:15 , group: 4, title:"Buzz"},
],eyeOfHorus: [
    {id:0 , group: 1, title:"Tiana"},
    {id:1 , group: 1, title:"Belle"},
    {id:2 , group: 1, title:"Mulan"},
    {id:3 , group: 1, title:"Jasmine"},
    {id:4 , group: 2, title:"Wild"},
    {id:5 , group: 2, title:"Brown"},
    {id:6 , group: 2, title:"White"},
    {id:7 , group: 2, title:"Basmati"},
    {id:8 , group: 3, title:"Message"},
    {id:9 , group: 3, title:"Skate"},
    {id:10 , group: 3, title:"Circuit"},
    {id:11 , group: 3, title:"Chess"},
    {id:12 , group: 4, title:"Rocketry"},
    {id:13 , group: 4, title:"Popular Vote"},
    {id:14 , group: 4, title:"Rapunzel"},
    {id:15 , group: 4, title:"Discontinue"},
],twistedFlax: [
    {id:0 , group: 1, title:"Ton"},
    {id:1 , group: 1, title:"Ounce"},
    {id:2 , group: 1, title:"Stone"},
    {id:3 , group: 1, title:"Gram"},
    {id:4 , group: 2, title:"Rand"},
    {id:5 , group: 2, title:"Ruble"},
    {id:6 , group: 2, title:"Pound"},
    {id:7 , group: 2, title:"Krona"},
    {id:8 , group: 3, title:"Electric"},
    {id:9 , group: 3, title:"Buffalo"},
    {id:10 , group: 3, title:"Legislative"},
    {id:11 , group: 3, title:"Dollar"},
    {id:12 , group: 4, title:"Vision"},
    {id:13 , group: 4, title:"Port"},
    {id:14 , group: 4, title:"Marketing"},
    {id:15 , group: 4, title:"Phone"},
],
hornedViper: [
    {id:0 , group: 1, title:"Gabriel"},
    {id:1 , group: 1, title:"Griffin"},
    {id:2 , group: 1, title:"Rabbit"},
    {id:3 , group: 1, title:"Jackson"},
    {id:4 , group: 2, title:"Fast"},
    {id:5 , group: 2, title:"Slaughterhouse"},
    {id:6 , group: 2, title:"High"},
    {id:7 , group: 2, title:"Maroon"},
    {id:8 , group: 3, title:"Crawdad"},
    {id:9 , group: 3, title:"Haunt"},
    {id:10 , group: 3, title:"Cardamom"},
    {id:11 , group: 3, title:"Carbuncle"},
    {id:12 , group: 4, title:"Cerberus"},
    {id:13 , group: 4, title:"Spectre"},
    {id:14 , group: 4, title:"Hydra"},
    {id:15 , group: 4, title:"Cobra"},
]
}
export {
    wallQuestions
}